spring.application.name=short-url
spring.datasource.url=jdbc:postgresql://localhost:5432/short_url
spring.datasource.username=root
spring.datasource.password=

spring.flyway.locations=classpath:db/migrations

api.security.token.secret=my-secret-token

app.base62.salt=${APP_BASE62_SALT}
app.feistel.xorMask=${APP_FEISTEL_XOR_MASK}